### ISSUE TITLE
Camunda properties are missing in Property Panel

### ISSUE THREAD

**Issue by suneetk92** [narve/ang2-bpmnjs#1]
Hey,
Thanks for the application, I was trying out the angular2 application and found that Camunda properties are missing in the Property panel.

Is it possible to integrate it in this application?

Thanks

**Comment by narve** [comment]
Hi @suneetk92 , for some reason I didn't get an email notification about this issue, apologise for the late answer. You've probably found your answer already, but anyway: 

- If by "Camunda properties" you mean the standard bpmn properties (id, name, documentation), then yes, they should be there as long as you call e.g. `createGeneralTabGroups` in props-provider.js. I believe I do that in the version pushed here. 

- If you mean Camunda-specific extensions, then the answer is "probably" - I haven't looked into that. I use the standard bpmn-properties and my own extensions.
